-- Migracion 179: Catalogo de servicios federados - fuentes ES + traducciones EN
--
-- El catalogo vive en codigo Go (internal/api/services_catalog.go) con texto
-- fuente en espanol. Aqui se registran las fuentes en content_translation_sources
-- (dominio '__GLOBAL__') y se siembran las traducciones en ingles, para que el
-- endpoint /api/services/catalog respete el idioma y las entradas aparezcan
-- en el modulo de traducciones (entity_type 'service_catalog').
-- Idempotente: ON CONFLICT en ambas inserciones.

DO $$
BEGIN
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'peertube', 'name', 'es', 'PeerTube', '{"label": "PeerTube", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'peertube', 'what_is', 'es', 'Plataforma de videos donde cualquiera puede subir, ver y compartir videos. Los videos se almacenan en el servidor de tu aldea, no en servidores corporativos. Las aldeas pueden federarse y ver videos entre ellas.', '{"label": "PeerTube", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'peertube', 'used_for', 'es', 'Subir videos de la aldea, tutoriales de agricultura, asambleas grabadas, documentales educativos, musica local. Sin anuncios, sin algoritmos que deciden que ver, sin recopilacion de datos.', '{"label": "PeerTube", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'peertube', 'replaces', 'es', 'YouTube', '{"label": "PeerTube", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mastodon', 'name', 'es', 'Mastodon', '{"label": "Mastodon", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mastodon', 'what_is', 'es', 'Red social de mensajes cortos (hasta 500 caracteres). Cada aldea tiene su propio servidor. Los miembros publican mensajes, siguen a otros, responden. Las aldeas federadas pueden ver y responder mensajes entre ellas.', '{"label": "Mastodon", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mastodon', 'used_for', 'es', 'Comunicacion rapida de la aldea, anuncios, debates, seguir noticias de otras aldeas. Sin anuncios, sin algoritmos, sin empresas vigilando.', '{"label": "Mastodon", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mastodon', 'replaces', 'es', 'Twitter / X', '{"label": "Mastodon", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'pixelfed', 'name', 'es', 'Pixelfed', '{"label": "Pixelfed", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'pixelfed', 'what_is', 'es', 'Red social de fotografias. Subes fotos, las compartes, sigues a otras personas, das ''me gusta''. Parecido a Instagram pero sin anuncios ni vigilancia. Las aldeas federadas pueden ver fotos entre ellas.', '{"label": "Pixelfed", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'pixelfed', 'used_for', 'es', 'Compartir fotos de la aldea, cosechas, talleres, eventos, paisajes. Sin filtros que alteran tu imagen, sin anuncios, sin recopilacion de datos.', '{"label": "Pixelfed", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'pixelfed', 'replaces', 'es', 'Instagram', '{"label": "Pixelfed", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'friendica', 'name', 'es', 'Friendica', '{"label": "Friendica", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'friendica', 'what_is', 'es', 'Red social completa con perfiles, grupos, eventos, mensajes privados, foros. Mas parecida a una red social tradicional. Puede conectarse con Mastodon, Diaspora y otras redes. Las aldeas federadas comparten contenido entre ellas.', '{"label": "Friendica", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'friendica', 'used_for', 'es', 'Crear grupos de la aldea (ej: ''Grupo de Agricultores'', ''Grupo de Mujeres''), organizar eventos, debates mas largos que Mastodon, mensajes privados. Sin anuncios, sin vigilancia, sin vender tus datos.', '{"label": "Friendica", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'friendica', 'replaces', 'es', 'Facebook', '{"label": "Friendica", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'lemmy', 'name', 'es', 'Lemmy', '{"label": "Lemmy", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'lemmy', 'what_is', 'es', 'Plataforma de foros y discusiones donde la gente publica enlaces, hace preguntas, responde, y vota las mejores respuestas. Los temas se organizan en ''comunidades'' (ej: ''agricultura'', ''construccion'', ''salud''). Las aldeas federadas comparten comunidades entre ellas.', '{"label": "Lemmy", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'lemmy', 'used_for', 'es', 'Foros de discusion por tema, preguntas y respuestas, compartir conocimientos tecnicos. La comunidad vota lo util que es cada respuesta. Sin anuncios, sin empresas manipulando que ves.', '{"label": "Lemmy", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'lemmy', 'replaces', 'es', 'Reddit', '{"label": "Lemmy", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bookwyrm', 'name', 'es', 'BookWyrm', '{"label": "BookWyrm", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bookwyrm', 'what_is', 'es', 'Red social para amantes de los libros. Llevas un registro de los libros que lees, los calificas, escribes resenas, creas listas de lectura, y descubres libros que otros recomiendan. Las aldeas federadas comparten resenas entre ellas.', '{"label": "BookWyrm", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bookwyrm', 'used_for', 'es', 'La biblioteca de la aldea puede llevar registro de los libros disponibles. Los miembros pueden recomendar libros, crear clubes de lectura, descubrir que leer. Sin que Amazon (dueno de Goodreads) vigile tus lecturas.', '{"label": "BookWyrm", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bookwyrm', 'replaces', 'es', 'Goodreads (pagina web donde la gente lleva registro de libros leidos y califica libros)', '{"label": "BookWyrm", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'writefreely', 'name', 'es', 'WriteFreely', '{"label": "WriteFreely", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'writefreely', 'what_is', 'es', 'Plataforma de blogs minimalista para escribir y publicar articulos, ensayos, historias, tutoriales. Sin distracciones, foco en la escritura. Los blogs se pueden federar con otras aldeas.', '{"label": "WriteFreely", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'writefreely', 'used_for', 'es', 'Escribir articulos largos, manuales, historias de la aldea, reflexiones, tutoriales. Publicar sin anuncios, sin ventanas emergentes, sin empresas monetizando tu contenido.', '{"label": "WriteFreely", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'writefreely', 'replaces', 'es', 'Medium, Blogger, WordPress.com', '{"label": "WriteFreely", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mobilizon', 'name', 'es', 'Mobilizon', '{"label": "Mobilizon", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mobilizon', 'what_is', 'es', 'Plataforma para crear y gestionar eventos. Creas un evento, pones fecha, lugar, descripcion, y la gente se inscribe. Parecido a la seccion de eventos de Facebook pero sin Facebook.', '{"label": "Mobilizon", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mobilizon', 'used_for', 'es', 'Organizar asambleas, talleres, fiestas, mingas, reuniones. La gente se inscribe sin necesidad de tener Facebook. Las aldeas federadas pueden ver eventos de otras aldeas.', '{"label": "Mobilizon", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mobilizon', 'replaces', 'es', 'Facebook Events, Eventbrite', '{"label": "Mobilizon", "category": "social"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'matrix', 'name', 'es', 'Matrix (Synapse)', '{"label": "Matrix (Synapse)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'matrix', 'what_is', 'es', 'Sistema de mensajeria descentralizado. Cada aldea tiene su propio servidor de mensajeria. Los miembros chatean en grupo o privado, envian archivos, hacen llamadas de voz y video. Las aldeas federadas pueden chatear entre ellas.', '{"label": "Matrix (Synapse)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'matrix', 'used_for', 'es', 'Mensajeria privada de la aldea, grupos de trabajo, coordinacion, envio de documentos. Sin que Meta (dueno de WhatsApp) lea tus mensajes ni venda tus datos. Tus mensajes se quedan en el servidor de tu aldea.', '{"label": "Matrix (Synapse)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'matrix', 'replaces', 'es', 'WhatsApp, Telegram, Signal', '{"label": "Matrix (Synapse)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'jitsi', 'name', 'es', 'Jitsi Meet', '{"label": "Jitsi Meet", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'jitsi', 'what_is', 'es', 'Plataforma de videoconferencias. Creas una sala, compartes el enlace, y la gente se conecta desde el navegador. Sin instalar nada. Soporta presentaciones de pantalla, grabacion, chat.', '{"label": "Jitsi Meet", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'jitsi', 'used_for', 'es', 'Reuniones virtuales de la asamblea, talleres en linea, educacion a distancia, reuniones con otras aldeas. Sin limite de tiempo, sin pagar suscripcion, sin que Zoom grabe tus reuniones.', '{"label": "Jitsi Meet", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'jitsi', 'replaces', 'es', 'Zoom, Google Meet, Microsoft Teams', '{"label": "Jitsi Meet", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'voip', 'name', 'es', 'Asterisk + FreePBX (Telefonia VoIP)', '{"label": "Asterisk + FreePBX (Telefonia VoIP)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'voip', 'what_is', 'es', 'Sistema telefonico completo para la aldea. Cada miembro tiene un numero de extension telefonica (ej: 2001, 2002). Se pueden hacer llamadas internas gratis. Con un codigo de aldea unico, se pueden llamar a miembros de otras aldeas federadas marcando el codigo de la aldea + el numero.', '{"label": "Asterisk + FreePBX (Telefonia VoIP)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'voip', 'used_for', 'es', 'Telefonos internos de la aldea sin pagar mensualidad a una compania. Llamadas entre aldeas federadas gratis por la intranet. Cada aldea tiene su codigo unico (ej: aldea 101, aldea 102). Para llamar de la aldea 101 a la 102, marcas 102-2001. Funciona con telefonos IP, telefonos analogos con adaptador, o apps en el celular.', '{"label": "Asterisk + FreePBX (Telefonia VoIP)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'voip', 'replaces', 'es', 'Lineas telefonicas tradicionales (compania telefonica)', '{"label": "Asterisk + FreePBX (Telefonia VoIP)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'sylk', 'name', 'es', 'Sylk Suite (Blink + SylkServer)', '{"label": "Sylk Suite (Blink + SylkServer)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'sylk', 'what_is', 'es', 'Suite completa de comunicacion en tiempo real basada en estandares abiertos SIP y MSRP. Incluye mensajeria chat individual y grupal, envio de archivos e imagenes, llamadas de voz y video, videoconferencias multiusuario, compartir pantalla y notificaciones push. El cliente Sylk esta disponible para Android, iOS, Windows, macOS y Linux. Tambien funciona desde el navegador web. Cifrado de extremo a extremo con zRTP para audio/video y OpenPGP para mensajes. Se conecta al servidor colocando el dominio del nodo y el cliente se configura automaticamente.', '{"label": "Sylk Suite (Blink + SylkServer)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'sylk', 'used_for', 'es', 'Mensajeria, llamadas y videoconferencias federadas entre aldeas. Cada miembro instala Sylk en su celular o computadora, coloca el dominio del nodo y se conecta automaticamente. Las aldeas federadas pueden llamarse y mensajearse entre si como si fuera correo electronico: sip:usuario@aldea-a.com llama a sip:amigo@aldea-b.com. Las salas grupales soportan chat, archivos, audio, video y pantalla compartida. Funciona con DNS SRV para resolver automaticamente la direccion del servidor destino.', '{"label": "Sylk Suite (Blink + SylkServer)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'sylk', 'replaces', 'es', 'WhatsApp, Telegram, Signal, Zoom, Google Meet, Microsoft Teams (mensajeria + llamadas + video en una sola app)', '{"label": "Sylk Suite (Blink + SylkServer)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mumble', 'name', 'es', 'Mumble', '{"label": "Mumble", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mumble', 'what_is', 'es', 'Sistema de voz en grupo de baja latencia. Creas un canal, la gente se conecta, y hablan como en una llamada grupal pero con mejor calidad y menos consumo. Parecido a Discord pero sin anuncios ni vigilancia.', '{"label": "Mumble", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mumble', 'used_for', 'es', 'Comunicacion de voz en tiempo real para trabajo en campo, coordinacion de mingas, radio de la aldea. Funciona bien con internet lento. Sin anuncios, sin empresas escuchando.', '{"label": "Mumble", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mumble', 'replaces', 'es', 'Discord (canal de voz), TeamSpeak', '{"label": "Mumble", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mailu', 'name', 'es', 'Mailu (Servidor de Correo Ligero)', '{"label": "Mailu (Servidor de Correo Ligero)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mailu', 'what_is', 'es', 'Servidor de correo completo 100% libre (licencia MIT, sin restricciones). Todo en uno: SMTP para enviar, IMAP para recibir, panel de administracion web para crear buzones y dominios, y webmail integrado para leer correo desde el navegador. Incluye antispam, antivirus, certificados SSL automaticos con Let''s Encrypt y federacion entre servidores de correo. Cada miembro tiene su correo con el dominio del nodo (ej: maria@mi-aldea.com). Solo necesita 1-2 GB de RAM. Ideal para nodos con hardware limitado.', '{"label": "Mailu (Servidor de Correo Ligero)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mailu', 'used_for', 'es', 'Correo electronico propio de la aldea. Cada miembro tiene su direccion @tu-dominio. Enviar y recibir correos de cualquier parte del mundo. Federacion automatica con otros servidores de correo via SMTP. Webmail para leer desde el navegador sin instalar nada. Panel admin para crear cuentas, configurar cuotas de espacio por usuario, definir dominios y aliases. Configuracion de clientes: IMAP (puerto 993 SSL), SMTP (puerto 587 STARTTLS), servidor: correo.tu-dominio. Los clientes de correo como Thunderbird, K-9 Mail (Android), Mail (iOS) se autoconfiguran via Autoconfig/Autodiscover.', '{"label": "Mailu (Servidor de Correo Ligero)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mailu', 'replaces', 'es', 'Gmail, Outlook, Yahoo Mail, ProtonMail (servidor de correo completo)', '{"label": "Mailu (Servidor de Correo Ligero)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mailcow', 'name', 'es', 'Mailcow (Servidor de Correo Completo)', '{"label": "Mailcow (Servidor de Correo Completo)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mailcow', 'what_is', 'es', 'Suite completa de correo lista para produccion empaquetada en Docker Compose. Incluye SOGo (webmail moderno con calendario compartido y contactos CardDAV/CalDAV), panel web administrativo para dar de alta buzones, dominios y certificados SSL automaticos. Mas completo que Mailu pero requiere mas recursos (3-4 GB RAM). Ideal para instalar en un servidor dedicado o en otro nodo con mas hardware. Incluye antispam (Rspamd), antivirus (ClamAV), sincronizacion de calendarios y contactos entre dispositivos.', '{"label": "Mailcow (Servidor de Correo Completo)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mailcow', 'used_for', 'es', 'Correo electronico completo con groupware: correo, calendario compartido, contactos sincronizados entre dispositivos, tareas. Cada miembro tiene su direccion @tu-dominio. Panel admin para crear cuentas, configurar cuotas de espacio por usuario, definir dominios, aliases y filtros. Configuracion de clientes: IMAP (puerto 993 SSL), SMTP (puerto 587 STARTTLS), CalDAV/CardDAV para calendario y contactos. Autoconfiguracion via Autodiscover. Recomendado para instalar en un servidor con mas RAM (puede ser otro nodo o servidor dedicado).', '{"label": "Mailcow (Servidor de Correo Completo)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mailcow', 'replaces', 'es', 'Gmail (calendario + contactos + correo), Outlook 365, Zoho Mail (suite completa con groupware)', '{"label": "Mailcow (Servidor de Correo Completo)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'deltachat', 'name', 'es', 'Delta Chat (Cliente de Chat por Correo)', '{"label": "Delta Chat (Cliente de Chat por Correo)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'deltachat', 'what_is', 'es', 'CLIENTE de mensajeria instantanea (no es un servidor) que funciona 100% sobre servidores de correo estandar. La app se ve y funciona identica a WhatsApp o Telegram, pero envia y recibe mensajes a traves de cuentas de email. Cifrado de extremo a extremo auditable. Clientes para Android, iOS, Windows, macOS y Linux. REQUIERE un servidor de correo (como Mailu o Mailcow) para funcionar: no tiene servidor propio. Se instala en el celular o computadora de cada miembro, no en el servidor del nodo.', '{"label": "Delta Chat (Cliente de Chat por Correo)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'deltachat', 'used_for', 'es', 'Chat de la aldea que se ve como WhatsApp pero sin empresas. Mensajes, fotos, archivos, grupos, llamadas de voz P2P. Federacion automatica: usuario@aldea-a.com chatea con amigo@aldea-b.com como si fuera un correo mas. Multi-dispositivo. Notificaciones push. Cero datos privados en el servidor. Para usarlo: 1) Instala Mailu o Mailcow en el nodo. 2) Crea una cuenta de correo para cada miembro. 3) Cada miembro instala Delta Chat en su celular. 4) En Delta Chat, coloca su correo@tu-dominio y contrasena. 5) Delta Chat se conecta automaticamente al servidor IMAP/SMTP del nodo. No hay que configurar servidores manualmente.', '{"label": "Delta Chat (Cliente de Chat por Correo)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'deltachat', 'replaces', 'es', 'WhatsApp, Telegram, Signal (mensajeria instantanea federada via correo)', '{"label": "Delta Chat (Cliente de Chat por Correo)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'snappymail', 'name', 'es', 'SnappyMail (Webmail)', '{"label": "SnappyMail (Webmail)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'snappymail', 'what_is', 'es', 'Cliente webmail rapido y moderno para leer correo desde el navegador. Interfaz estilo Gmail, adaptable a moviles. Se conecta a cualquier servidor IMAP/SMTP (como Mailu o Mailcow). Soporta multiples cuentas, filtros, busqueda, contactos y calendario. Ligero y rapido. No es un servidor: es la interfaz web que los miembros usan para leer su correo sin instalar una app.', '{"label": "SnappyMail (Webmail)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'snappymail', 'used_for', 'es', 'Dar a los miembros una interfaz web para leer y escribir correos sin instalar ningun programa. Se abre desde el navegador del celular o computadora en webmail.tu-dominio. Ideal para miembros que no quieren instalar una app de correo. Se conecta al servidor de correo del nodo (Mailu o Mailcow). Configuracion: el admin configura la conexion IMAP/SMTP al servidor de correo del nodo. Los usuarios solo entran con su correo@tu-dominio y contrasena.', '{"label": "SnappyMail (Webmail)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'snappymail', 'replaces', 'es', 'Gmail (interfaz web), Outlook Web (interfaz web de correo)', '{"label": "SnappyMail (Webmail)", "category": "comunicacion"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'nextcloud', 'name', 'es', 'Nextcloud', '{"label": "Nextcloud", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'nextcloud', 'what_is', 'es', 'Almacenamiento de archivos en la nube. Cada miembro tiene su carpeta privada donde puede guardar documentos, fotos, videos. Se pueden compartir carpetas con otros. Incluye calendario, contactos, tareas. Todo se almacena en el servidor de la aldea.', '{"label": "Nextcloud", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'nextcloud', 'used_for', 'es', 'Guardar documentos de la aldea, compartir archivos entre miembros, calendario comunitario, contactos. Sin pagar suscripcion mensual, sin que Google o Apple tengan acceso a tus archivos. Tus datos se quedan en la aldea.', '{"label": "Nextcloud", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'nextcloud', 'replaces', 'es', 'Google Drive, Dropbox, iCloud, OneDrive', '{"label": "Nextcloud", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'collabora', 'name', 'es', 'Collabora / Nextcloud Office', '{"label": "Collabora / Nextcloud Office", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'collabora', 'what_is', 'es', 'Suite ofimatica en el navegador. Crear y editar documentos de texto, hojas de calculo, presentaciones. Trabajo colaborativo en tiempo real (varias personas editando el mismo documento a la vez). Se integra con Nextcloud.', '{"label": "Collabora / Nextcloud Office", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'collabora', 'used_for', 'es', 'Escribir documentos de la asamblea, llevar planillas de contabilidad, crear presentaciones para talleres. Trabajo colaborativo sin Google ni Microsoft vigilando tu contenido.', '{"label": "Collabora / Nextcloud Office", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'collabora', 'replaces', 'es', 'Google Docs, Google Sheets, Google Slides, Microsoft Office Online', '{"label": "Collabora / Nextcloud Office", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bookstack', 'name', 'es', 'BookStack', '{"label": "BookStack", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bookstack', 'what_is', 'es', 'Plataforma de documentacion y wiki organizada como libros, capitulos y paginas. Facil de usar, no requiere conocimientos tecnicos. Busqueda integrada, control de permisos.', '{"label": "BookStack", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bookstack', 'used_for', 'es', 'Manual de la aldea, recetarios, guias de cultivo, procedimientos, reglamentos. Organizar el conocimiento de la aldea en un solo lugar. Facil de buscar y actualizar.', '{"label": "BookStack", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bookstack', 'replaces', 'es', 'Confluence, Notion (para documentacion)', '{"label": "BookStack", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mediawiki', 'name', 'es', 'MediaWiki', '{"label": "MediaWiki", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mediawiki', 'what_is', 'es', 'Software de wiki, el mismo que usa Wikipedia. Cualquiera puede crear y editar paginas. Historial de cambios, discusiones, categorias.', '{"label": "MediaWiki", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mediawiki', 'used_for', 'es', 'Enciclopedia interna de la aldea, documentacion colaborativa, base de conocimiento. Todos pueden contribuir. Igual que Wikipedia pero para tu aldea.', '{"label": "MediaWiki", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'mediawiki', 'replaces', 'es', 'Wikipedia (para conocimiento interno de la aldea)', '{"label": "MediaWiki", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'jellyfin', 'name', 'es', 'Jellyfin', '{"label": "Jellyfin", "category": "multimedia"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'jellyfin', 'what_is', 'es', 'Servidor de medios. Guardas tus peliculas, series, musica, fotos en el servidor y las reproduces desde cualquier dispositivo (TV, celular, computadora). Sin anuncios, sin suscripcion.', '{"label": "Jellyfin", "category": "multimedia"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'jellyfin', 'used_for', 'es', 'Cine de la aldea, biblioteca de musica, peliculas educativas, documentales. Cada miembro puede ver lo que quiera cuando quiera. Sin pagar Netflix, sin anuncios, sin algoritmos.', '{"label": "Jellyfin", "category": "multimedia"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'jellyfin', 'replaces', 'es', 'Netflix, Spotify, Plex', '{"label": "Jellyfin", "category": "multimedia"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'funkwhale', 'name', 'es', 'Funkwhale', '{"label": "Funkwhale", "category": "multimedia"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'funkwhale', 'what_is', 'es', 'Plataforma de musica federada. Subes musica, creas playlists, sigues artistas. Las aldeas federadas pueden compartir musica entre ellas. Parecido a Spotify pero sin anuncios ni empresas.', '{"label": "Funkwhale", "category": "multimedia"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'funkwhale', 'used_for', 'es', 'Compartir musica de la aldea, artistas locales, podcasts, grabaciones de asambleas. Descubrir musica de otras aldeas. Sin anuncios, sin algoritmos, sin empresas monetizando tu escucha.', '{"label": "Funkwhale", "category": "multimedia"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'funkwhale', 'replaces', 'es', 'Spotify, SoundCloud', '{"label": "Funkwhale", "category": "multimedia"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'gitea', 'name', 'es', 'Gitea / Forgejo', '{"label": "Gitea / Forgejo", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'gitea', 'what_is', 'es', 'Plataforma de gestion de codigo fuente. Hospeda repositorios git, control de versiones, issues, pull requests. Parecido a GitHub pero en tu propio servidor.', '{"label": "Gitea / Forgejo", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'gitea', 'used_for', 'es', 'Si alguien de la aldea programa, puede hospedar su codigo aqui. Tambien para versionar documentos importantes, configuraciones, manuales tecnicos. Sin depender de GitHub (empresa de Microsoft).', '{"label": "Gitea / Forgejo", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'gitea', 'replaces', 'es', 'GitHub, GitLab', '{"label": "Gitea / Forgejo", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bigbluebutton', 'name', 'es', 'BigBlueButton', '{"label": "BigBlueButton", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bigbluebutton', 'what_is', 'es', 'Plataforma de educacion virtual con pizarra, presentaciones, video, chat, grupos de trabajo. Disenada para ensenanza online.', '{"label": "BigBlueButton", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bigbluebutton', 'used_for', 'es', 'Clases virtuales de la escuela de la aldea, talleres en linea, capacitaciones. Pizarra compartida, presentaciones, grabacion de clases. Sin pagar Zoom, sin Google vigilando.', '{"label": "BigBlueButton", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'bigbluebutton', 'replaces', 'es', 'Zoom (para educacion), Google Classroom', '{"label": "BigBlueButton", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'homeassistant', 'name', 'es', 'Home Assistant', '{"label": "Home Assistant", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'homeassistant', 'what_is', 'es', 'Plataforma de automatizacion del hogar. Conecta dispositivos inteligentes (luces, sensores, cerraduras, energia solar, bombas de agua) y los controla desde un solo lugar. Funciona sin Internet.', '{"label": "Home Assistant", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'homeassistant', 'used_for', 'es', 'Automatizar luces, monitorear energia solar, controlar bombas de agua, sensores de temperatura, seguridad. Sin que Google o Amazon tengan acceso a tu casa. Todo se procesa localmente.', '{"label": "Home Assistant", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'homeassistant', 'replaces', 'es', 'Google Home, Amazon Alexa, SmartThings', '{"label": "Home Assistant", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'vaultwarden', 'name', 'es', 'Vaultwarden (Bitwarden)', '{"label": "Vaultwarden (Bitwarden)", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'vaultwarden', 'what_is', 'es', 'Gestor de contrasenas. Guarda todas tus contrasenas de forma cifrada en el servidor de la aldea. Autocompleta contrasenas en el navegador. Genera contrasenas seguras.', '{"label": "Vaultwarden (Bitwarden)", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'vaultwarden', 'used_for', 'es', 'Que cada miembro tenga un lugar seguro para sus contrasenas. No mas contrasenas escritas en papel o repetidas. Sincroniza entre dispositivos. Sin que empresas de terceros tengan tus contrasenas.', '{"label": "Vaultwarden (Bitwarden)", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'vaultwarden', 'replaces', 'es', 'LastPass, 1Password, Dashlane, gestor de contrasenas de Google/Apple', '{"label": "Vaultwarden (Bitwarden)", "category": "desarrollo"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'pos-web', 'name', 'es', 'Punto de Venta Web', '{"label": "Punto de Venta Web", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'pos-web', 'what_is', 'es', 'Terminal de punto de venta para cobrar con TQ (moneda de la red de intercambio federada). Se descarga e instala desde este nodo y se configura automaticamente con la direccion de este nodo. Puede cobrar a miembros de CUALQUIER nodo federado: si alguien de otra comunidad federada visita tu local, puede pagar con su tarjeta NFC o escaneando el QR. No es un POS generico: no sirve para cobrar con dinero tradicional, tarjetas bancarias, criptomonedas ni ningun otro sistema externo. Solo procesa TQ entre nodos federados. Se instala como aplicacion web (PWA) en cualquier dispositivo: celular, tablet o PC. Se registra como un terminal NFC mas del nodo, con claves criptograficas Ed25519 y huella de dispositivo.', '{"label": "Punto de Venta Web", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'pos-web', 'used_for', 'es', 'Cobrar ventas con TQ. El comerciante ingresa el monto en TQ, el cliente paga escaneando un QR con su celular o acercando su tarjeta NFC. El cliente puede ser de este nodo o de cualquier nodo federado. Las organizaciones pueden asignar terminales a miembros, ver turnos (quien uso el terminal y cuando), ventas por usuario y todas las transacciones. IMPORTANTE: Este POS solo procesa TQ. No procesa dinero real, tarjetas bancarias ni criptomonedas. Se descarga desde cada nodo y se configura con la direccion de ese nodo, pero acepta pagos de cualquier nodo federado.', '{"label": "Punto de Venta Web", "category": "productividad"}'::jsonb);
  PERFORM upsert_content_translation_source('__GLOBAL__', 'service_catalog', 'pos-web', 'replaces', 'es', 'Terminales POS comerciales (Solo para TQ, no para dinero tradicional)', '{"label": "Punto de Venta Web", "category": "productividad"}'::jsonb);
END $$;

-- Traducciones en ingles (source_hash se toma de la fuente ya registrada)
INSERT INTO content_translations (translation_key, language, value, source_hash, updated_at)
SELECT s.translation_key, 'en', v.value, s.source_hash, NOW()
FROM content_translation_sources s
JOIN (VALUES
  ('service_catalog:peertube:name', 'PeerTube'),
  ('service_catalog:peertube:what_is', 'Video platform where anyone can upload, watch and share videos. Videos are stored on your community''s server, not on corporate servers. Communities can federate and share videos between them.'),
  ('service_catalog:peertube:used_for', 'Upload community videos, farming tutorials, recorded assemblies, educational documentaries, local music. No ads, no algorithms deciding what to watch, no data collection.'),
  ('service_catalog:peertube:replaces', 'YouTube'),
  ('service_catalog:mastodon:name', 'Mastodon'),
  ('service_catalog:mastodon:what_is', 'Short-message social network (up to 500 characters). Each community has its own server. Members post messages, follow others, reply. Federated communities can see and reply to each other''s messages.'),
  ('service_catalog:mastodon:used_for', 'Quick community communication, announcements, debates, following news from other communities. No ads, no algorithms, no corporate surveillance.'),
  ('service_catalog:mastodon:replaces', 'Twitter / X'),
  ('service_catalog:pixelfed:name', 'Pixelfed'),
  ('service_catalog:pixelfed:what_is', 'Photo-sharing social network. Upload photos, share them, follow others, ''like'' posts. Similar to Instagram but without ads or surveillance. Federated communities can share photos between them.'),
  ('service_catalog:pixelfed:used_for', 'Share community photos, harvests, workshops, events, landscapes. No filters altering your images, no ads, no data collection.'),
  ('service_catalog:pixelfed:replaces', 'Instagram'),
  ('service_catalog:friendica:name', 'Friendica'),
  ('service_catalog:friendica:what_is', 'Full-featured social network with profiles, groups, events, private messages, forums. More similar to a traditional social network. Can connect with Mastodon, Diaspora and other networks. Federated communities share content between them.'),
  ('service_catalog:friendica:used_for', 'Create community groups (e.g. ''Farmers Group'', ''Women''s Group''), organize events, longer discussions than Mastodon, private messages. No ads, no surveillance, no selling your data.'),
  ('service_catalog:friendica:replaces', 'Facebook'),
  ('service_catalog:lemmy:name', 'Lemmy'),
  ('service_catalog:lemmy:what_is', 'Forum and discussion platform where people post links, ask questions, reply, and vote on the best answers. Topics are organized into ''communities'' (e.g. ''agriculture'', ''construction'', ''health''). Federated communities share forums between them.'),
  ('service_catalog:lemmy:used_for', 'Topic-based discussion forums, Q&A, sharing technical knowledge. The community votes on how useful each answer is. No ads, no companies manipulating what you see.'),
  ('service_catalog:lemmy:replaces', 'Reddit'),
  ('service_catalog:bookwyrm:name', 'BookWyrm'),
  ('service_catalog:bookwyrm:what_is', 'Social network for book lovers. Track books you read, rate them, write reviews, create reading lists, and discover books others recommend. Federated communities share reviews between them.'),
  ('service_catalog:bookwyrm:used_for', 'The community library can track available books. Members can recommend books, create reading clubs, discover what to read. Without Amazon (owner of Goodreads) tracking your reading habits.'),
  ('service_catalog:bookwyrm:replaces', 'Goodreads (website where people track books read and rate them)'),
  ('service_catalog:writefreely:name', 'WriteFreely'),
  ('service_catalog:writefreely:what_is', 'Minimalist blogging platform for writing and publishing articles, essays, stories, tutorials. No distractions, focused on writing. Blogs can be federated with other communities.'),
  ('service_catalog:writefreely:used_for', 'Write long-form articles, manuals, community stories, reflections, tutorials. Publish without ads, without pop-ups, without companies monetizing your content.'),
  ('service_catalog:writefreely:replaces', 'Medium, Blogger, WordPress.com'),
  ('service_catalog:mobilizon:name', 'Mobilizon'),
  ('service_catalog:mobilizon:what_is', 'Platform for creating and managing events. Create an event, set date, location, description, and people register. Similar to Facebook Events but without Facebook.'),
  ('service_catalog:mobilizon:used_for', 'Organize assemblies, workshops, parties, work bees, meetings. People register without needing Facebook. Federated communities can see events from other communities.'),
  ('service_catalog:mobilizon:replaces', 'Facebook Events, Eventbrite'),
  ('service_catalog:matrix:name', 'Matrix (Synapse)'),
  ('service_catalog:matrix:what_is', 'Decentralized messaging system. Each community has its own messaging server. Members chat in groups or privately, send files, make voice and video calls. Federated communities can chat with each other.'),
  ('service_catalog:matrix:used_for', 'Private community messaging, work groups, coordination, document sharing. Without Meta (owner of WhatsApp) reading your messages or selling your data. Your messages stay on your community''s server.'),
  ('service_catalog:matrix:replaces', 'WhatsApp, Telegram, Signal'),
  ('service_catalog:jitsi:name', 'Jitsi Meet'),
  ('service_catalog:jitsi:what_is', 'Videoconferencing platform. Create a room, share the link, and people join from their browser. No installation needed. Supports screen sharing, recording, chat.'),
  ('service_catalog:jitsi:used_for', 'Virtual assembly meetings, online workshops, distance education, meetings with other communities. No time limits, no subscription fees, no Zoom recording your meetings.'),
  ('service_catalog:jitsi:replaces', 'Zoom, Google Meet, Microsoft Teams'),
  ('service_catalog:voip:name', 'Asterisk + FreePBX (VoIP Telephony)'),
  ('service_catalog:voip:what_is', 'Complete telephone system for the community. Each member has a phone extension number (e.g. 2001, 2002). Internal calls are free. With a unique community code, members can call other federated communities by dialing the community code + number.'),
  ('service_catalog:voip:used_for', 'Internal community phones without paying monthly fees to a phone company. Free calls between federated communities over the intranet. Each community has its unique code (e.g. community 101, community 102). To call from community 101 to 102, dial 102-2001. Works with IP phones, analog phones with adapter, or mobile apps.'),
  ('service_catalog:voip:replaces', 'Traditional phone lines (phone company)'),
  ('service_catalog:sylk:name', 'Sylk Suite (Blink + SylkServer)'),
  ('service_catalog:sylk:what_is', 'Complete real-time communication suite based on open SIP and MSRP standards. Includes individual and group chat messaging, file and image sharing, voice and video calls, multi-party videoconferencing, screen sharing and push notifications. The Sylk client is available for Android, iOS, Windows, macOS and Linux. Also works from the web browser. End-to-end encryption with zRTP for audio/video and OpenPGP for messages. Connects to the server by entering the node domain and the client auto-configures.'),
  ('service_catalog:sylk:used_for', 'Federated messaging, calls and videoconferencing between communities. Each member installs Sylk on their phone or computer, enters the node domain and connects automatically. Federated communities can call and message each other like email: sip:user@community-a.com calls sip:friend@community-b.com. Group rooms support chat, files, audio, video and screen sharing. Works with DNS SRV to automatically resolve the destination server address.'),
  ('service_catalog:sylk:replaces', 'WhatsApp, Telegram, Signal, Zoom, Google Meet, Microsoft Teams (messaging + calls + video in one app)'),
  ('service_catalog:mumble:name', 'Mumble'),
  ('service_catalog:mumble:what_is', 'Low-latency group voice chat. Create a channel, people join, and talk like in a group call but with better quality and lower resource usage. Similar to Discord but without ads or surveillance.'),
  ('service_catalog:mumble:used_for', 'Real-time voice communication for field work, coordinating work bees, community radio. Works well with slow internet. No ads, no companies listening.'),
  ('service_catalog:mumble:replaces', 'Discord (voice channel), TeamSpeak'),
  ('service_catalog:mailu:name', 'Mailu (Lightweight Mail Server)'),
  ('service_catalog:mailu:what_is', 'Complete 100% free mail server (MIT license, no restrictions). All-in-one: SMTP for sending, IMAP for receiving, web admin panel for creating mailboxes and domains, and integrated webmail for reading email from the browser. Includes antispam, antivirus, automatic SSL certificates with Let''s Encrypt and federation between mail servers. Each member has their email with the node domain (e.g. maria@my-community.com). Only needs 1-2 GB RAM. Ideal for nodes with limited hardware.'),
  ('service_catalog:mailu:used_for', 'Community''s own email. Each member has their @your-domain address. Send and receive emails from anywhere in the world. Automatic federation with other mail servers via SMTP. Webmail to read from browser without installing anything. Admin panel to create accounts, configure storage quotas per user, define domains and aliases. Client configuration: IMAP (port 993 SSL), SMTP (port 587 STARTTLS), server: mail.your-domain. Email clients like Thunderbird, K-9 Mail (Android), Mail (iOS) auto-configure via Autoconfig/Autodiscover.'),
  ('service_catalog:mailu:replaces', 'Gmail, Outlook, Yahoo Mail, ProtonMail (complete mail server)'),
  ('service_catalog:mailcow:name', 'Mailcow (Complete Mail Server)'),
  ('service_catalog:mailcow:what_is', 'Production-ready complete mail suite packaged in Docker Compose. Includes SOGo (modern webmail with shared calendar and CardDAV/CalDAV contacts), web admin panel for creating mailboxes, domains and automatic SSL certificates. More complete than Mailu but requires more resources (3-4 GB RAM). Ideal for installing on a dedicated server or another node with more hardware. Includes antispam (Rspamd), antivirus (ClamAV), calendar and contact sync between devices.'),
  ('service_catalog:mailcow:used_for', 'Complete email with groupware: email, shared calendar, contacts synced between devices, tasks. Each member has their @your-domain address. Admin panel to create accounts, configure storage quotas per user, define domains, aliases and filters. Client configuration: IMAP (port 993 SSL), SMTP (port 587 STARTTLS), CalDAV/CardDAV for calendar and contacts. Auto-configuration via Autodiscover. Recommended for installing on a server with more RAM (can be another node or dedicated server).'),
  ('service_catalog:mailcow:replaces', 'Gmail (calendar + contacts + email), Outlook 365, Zoho Mail (complete suite with groupware)'),
  ('service_catalog:deltachat:name', 'Delta Chat (Chat Client over Email)'),
  ('service_catalog:deltachat:what_is', 'Instant messaging CLIENT (not a server) that works 100% over standard email servers. The app looks and works exactly like WhatsApp or Telegram, but sends and receives messages through email accounts. Auditable end-to-end encryption. Clients for Android, iOS, Windows, macOS and Linux. REQUIRES a mail server (like Mailu or Mailcow) to work: it has no server of its own. Installed on each member''s phone or computer, not on the node server.'),
  ('service_catalog:deltachat:used_for', 'Community chat that looks like WhatsApp but without corporations. Messages, photos, files, groups, P2P voice calls. Automatic federation: user@community-a.com chats with friend@community-b.com like regular email. Multi-device. Push notifications. Zero private data on server. To use: 1) Install Mailu or Mailcow on the node. 2) Create an email account for each member. 3) Each member installs Delta Chat on their phone. 4) In Delta Chat, enter their email@your-domain and password. 5) Delta Chat auto-connects to the node''s IMAP/SMTP server. No manual server configuration needed.'),
  ('service_catalog:deltachat:replaces', 'WhatsApp, Telegram, Signal (federated instant messaging via email)'),
  ('service_catalog:snappymail:name', 'SnappyMail (Webmail)'),
  ('service_catalog:snappymail:what_is', 'Fast and modern webmail client for reading email from the browser. Gmail-style interface, mobile-friendly. Connects to any IMAP/SMTP server (like Mailu or Mailcow). Supports multiple accounts, filters, search, contacts and calendar. Lightweight and fast. Not a server: it''s the web interface members use to read email without installing an app.'),
  ('service_catalog:snappymail:used_for', 'Give members a web interface to read and write emails without installing any software. Open from browser on phone or computer at webmail.your-domain. Ideal for members who don''t want to install an email app. Connects to the node''s mail server (Mailu or Mailcow). Configuration: admin sets up IMAP/SMTP connection to the node''s mail server. Users just log in with their email@your-domain and password.'),
  ('service_catalog:snappymail:replaces', 'Gmail (web interface), Outlook Web (web email interface)'),
  ('service_catalog:nextcloud:name', 'Nextcloud'),
  ('service_catalog:nextcloud:what_is', 'Cloud file storage. Each member has a private folder for documents, photos, videos. Folders can be shared with others. Includes calendar, contacts, tasks. Everything stored on the community''s server.'),
  ('service_catalog:nextcloud:used_for', 'Store community documents, share files between members, community calendar, contacts. No monthly subscription, no Google or Apple accessing your files. Your data stays in the community.'),
  ('service_catalog:nextcloud:replaces', 'Google Drive, Dropbox, iCloud, OneDrive'),
  ('service_catalog:collabora:name', 'Collabora / Nextcloud Office'),
  ('service_catalog:collabora:what_is', 'Office suite in the browser. Create and edit text documents, spreadsheets, presentations. Real-time collaborative editing (multiple people editing the same document at once). Integrates with Nextcloud.'),
  ('service_catalog:collabora:used_for', 'Write assembly documents, maintain accounting spreadsheets, create workshop presentations. Collaborative work without Google or Microsoft monitoring your content.'),
  ('service_catalog:collabora:replaces', 'Google Docs, Google Sheets, Google Slides, Microsoft Office Online'),
  ('service_catalog:bookstack:name', 'BookStack'),
  ('service_catalog:bookstack:what_is', 'Documentation and wiki platform organized as books, chapters and pages. Easy to use, no technical knowledge required. Integrated search, permission control.'),
  ('service_catalog:bookstack:used_for', 'Community manual, recipe collections, growing guides, procedures, regulations. Organize community knowledge in one place. Easy to search and update.'),
  ('service_catalog:bookstack:replaces', 'Confluence, Notion (for documentation)'),
  ('service_catalog:mediawiki:name', 'MediaWiki'),
  ('service_catalog:mediawiki:what_is', 'Wiki software, the same one used by Wikipedia. Anyone can create and edit pages. Change history, discussions, categories.'),
  ('service_catalog:mediawiki:used_for', 'Internal community encyclopedia, collaborative documentation, knowledge base. Everyone can contribute. Like Wikipedia but for your community.'),
  ('service_catalog:mediawiki:replaces', 'Wikipedia (for internal community knowledge)'),
  ('service_catalog:jellyfin:name', 'Jellyfin'),
  ('service_catalog:jellyfin:what_is', 'Media server. Store movies, series, music, photos on the server and stream them to any device (TV, phone, computer). No ads, no subscription.'),
  ('service_catalog:jellyfin:used_for', 'Community cinema, music library, educational films, documentaries. Each member can watch what they want when they want. No Netflix fees, no ads, no algorithms.'),
  ('service_catalog:jellyfin:replaces', 'Netflix, Spotify, Plex'),
  ('service_catalog:funkwhale:name', 'Funkwhale'),
  ('service_catalog:funkwhale:what_is', 'Federated music platform. Upload music, create playlists, follow artists. Federated communities can share music between them. Similar to Spotify but without ads or corporations.'),
  ('service_catalog:funkwhale:used_for', 'Share community music, local artists, podcasts, assembly recordings. Discover music from other communities. No ads, no algorithms, no companies monetizing your listening.'),
  ('service_catalog:funkwhale:replaces', 'Spotify, SoundCloud'),
  ('service_catalog:gitea:name', 'Gitea / Forgejo'),
  ('service_catalog:gitea:what_is', 'Source code management platform. Host git repositories, version control, issues, pull requests. Similar to GitHub but on your own server.'),
  ('service_catalog:gitea:used_for', 'If anyone in the community codes, they can host their code here. Also for versioning important documents, configurations, technical manuals. Without depending on GitHub (Microsoft-owned).'),
  ('service_catalog:gitea:replaces', 'GitHub, GitLab'),
  ('service_catalog:bigbluebutton:name', 'BigBlueButton'),
  ('service_catalog:bigbluebutton:what_is', 'Virtual education platform with whiteboard, presentations, video, chat, breakout groups. Designed for online teaching.'),
  ('service_catalog:bigbluebutton:used_for', 'Virtual classes for the community school, online workshops, training. Shared whiteboard, presentations, class recording. No Zoom fees, no Google surveillance.'),
  ('service_catalog:bigbluebutton:replaces', 'Zoom (for education), Google Classroom'),
  ('service_catalog:homeassistant:name', 'Home Assistant'),
  ('service_catalog:homeassistant:what_is', 'Home automation platform. Connects smart devices (lights, sensors, locks, solar energy, water pumps) and controls them from one place. Works without Internet.'),
  ('service_catalog:homeassistant:used_for', 'Automate lights, monitor solar energy, control water pumps, temperature sensors, security. Without Google or Amazon accessing your home. Everything processed locally.'),
  ('service_catalog:homeassistant:replaces', 'Google Home, Amazon Alexa, SmartThings'),
  ('service_catalog:vaultwarden:name', 'Vaultwarden (Bitwarden)'),
  ('service_catalog:vaultwarden:what_is', 'Password manager. Stores all your passwords encrypted on the community''s server. Auto-fills passwords in the browser. Generates strong passwords.'),
  ('service_catalog:vaultwarden:used_for', 'Give each member a secure place for their passwords. No more passwords on paper or reused. Syncs between devices. Without third-party companies having your passwords.'),
  ('service_catalog:vaultwarden:replaces', 'LastPass, 1Password, Dashlane, Google/Apple password manager'),
  ('service_catalog:pos-web:name', 'Web Point of Sale'),
  ('service_catalog:pos-web:what_is', 'Point of sale terminal for charging with TQ (the federated exchange network currency). Downloads and installs from this node and auto-configures with this node''s address. Can charge members from ANY federated node: if someone from another federated community visits your location, they can pay with their NFC card or by scanning the QR. This is not a generic POS: it doesn''t work for charging with traditional money, bank cards, cryptocurrencies or any other external system. It only processes TQ between federated nodes. Installs as a web app (PWA) on any device: phone, tablet or PC. Registers as an NFC terminal of the node, with Ed25519 cryptographic keys and device fingerprint.'),
  ('service_catalog:pos-web:used_for', 'Charge sales with TQ. The merchant enters the amount in TQ, the customer pays by scanning a QR with their phone or tapping their NFC card. The customer can be from this node or any federated node. Organizations can assign terminals to members, view shifts (who used the terminal and when), sales by user and all transactions. IMPORTANT: This POS only processes TQ. It does not process real money, bank cards or cryptocurrencies. Downloads from each node and configures with that node''s address, but accepts payments from any federated node.'),
  ('service_catalog:pos-web:replaces', 'Commercial POS terminals (TQ only, not for traditional money)')
) AS v(translation_key, value) ON v.translation_key = s.translation_key
ON CONFLICT (translation_key, language) DO UPDATE SET
  value = EXCLUDED.value,
  source_hash = EXCLUDED.source_hash,
  updated_at = NOW();
